package Napakalaki;
public class JDnombresJugadores extends javax.swing.JDialog {

    private String[] nombres;
    public JDnombresJugadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbCuatroJugadores = new javax.swing.JCheckBox();
        jljug1 = new javax.swing.JLabel();
        jljug2 = new javax.swing.JLabel();
        jljug3 = new javax.swing.JLabel();
        jljug4 = new javax.swing.JLabel();
        jtJug1 = new javax.swing.JTextField();
        jtJug2 = new javax.swing.JTextField();
        jtJug3 = new javax.swing.JTextField();
        jtJug4 = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jbComenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Escribe los nombres de los jugadores");

        jcbCuatroJugadores.setText("Cuatro jugadores");
        jcbCuatroJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCuatroJugadoresActionPerformed(evt);
            }
        });

        jljug1.setText("Jugador 1");

        jljug2.setText("Jugador 2");

        jljug3.setText("Jugador 3");

        jljug4.setText("Jugador 4");
        jljug4.setEnabled(false);

        jtJug1.setText("Ana0");
        jtJug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtJug1ActionPerformed(evt);
            }
        });

        jtJug2.setText("Pepe1");
        jtJug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtJug2ActionPerformed(evt);
            }
        });

        jtJug3.setText("Jose2");
        jtJug3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtJug3ActionPerformed(evt);
            }
        });

        jtJug4.setEditable(false);
        jtJug4.setText("Juan3");
        jtJug4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtJug4ActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbComenzar.setText("Comenzar");
        jbComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComenzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jljug3)
                        .addGap(18, 18, 18)
                        .addComponent(jtJug3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jljug1)
                        .addGap(18, 18, 18)
                        .addComponent(jtJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbCuatroJugadores)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbComenzar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jljug4)
                            .addGap(18, 18, 18)
                            .addComponent(jtJug4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jljug2)
                        .addGap(18, 18, 18)
                        .addComponent(jtJug2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jcbCuatroJugadores)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jljug1)
                    .addComponent(jtJug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jljug2)
                    .addComponent(jtJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jljug3)
                    .addComponent(jtJug3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jljug4)
                    .addComponent(jtJug4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbComenzar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtJug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtJug1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtJug1ActionPerformed

    private void jtJug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtJug2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtJug2ActionPerformed

    private void jtJug3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtJug3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtJug3ActionPerformed

    private void jtJug4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtJug4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtJug4ActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jcbCuatroJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCuatroJugadoresActionPerformed
    jljug4.setEnabled(jcbCuatroJugadores.isSelected());
    jtJug4.setEnabled(jcbCuatroJugadores.isSelected());
    jtJug4.setEditable(jcbCuatroJugadores.isSelected());
    repaint();
  
    }//GEN-LAST:event_jcbCuatroJugadoresActionPerformed

    private void jbComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComenzarActionPerformed
        if (jcbCuatroJugadores.isSelected()) {
            nombres = new String[4];
            nombres[0] = jtJug1.getText();
            nombres[1] = jtJug2.getText();
            nombres[2] = jtJug3.getText();
            nombres[3] = jtJug4.getText();
        } else {
            nombres = new String[3];
            nombres[0] = jtJug1.getText();
            nombres[1] = jtJug2.getText();
            nombres[2] = jtJug3.getText();
        }
        
        this.dispose();
    }//GEN-LAST:event_jbComenzarActionPerformed

    /**
     * @param args the command line arguments
     */

        public String[] getNombres() {
            this.setVisible(true);
            return nombres;
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbComenzar;
    private javax.swing.JCheckBox jcbCuatroJugadores;
    private javax.swing.JLabel jljug1;
    private javax.swing.JLabel jljug2;
    private javax.swing.JLabel jljug3;
    private javax.swing.JLabel jljug4;
    private javax.swing.JTextField jtJug1;
    private javax.swing.JTextField jtJug2;
    private javax.swing.JTextField jtJug3;
    private javax.swing.JTextField jtJug4;
    // End of variables declaration//GEN-END:variables
}
